openapi: 3.0.0
info:
  title: Shared.v1
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Problem:
      title: Problem
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
          minimum: 200
          maximum: 599
        detail:
          type: string
        instance:
          type: string
      required:
        - type
        - title
        - status
