version: "3"

services:
  universe-e2e-postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: universe
      POSTGRES_USER: universe
      POSTGRES_PASSWORD: universe

  universe-e2e-service:
    image: universe-service:latest
    environment:
      RUST_LOG: debug
      DATABASE_URL: postgres://universe:universe@universe-e2e-postgres:5432/universe
      DOCKERIZE_ARGS: -wait tcp://universe-e2e-postgres:5432
      PORT: 3000
    ports:
      - "127.0.0.1:3000:3000"
