name: CI

on:
  push:

jobs:
  test-service:
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: stable

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15.6"

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.2
          working-directory: service

      - name: Generate
        working-directory: service
        run: |
          go get -u github.com/gobuffalo/packr/v2/packr2
          go generate ./...

      - name: Unit Tests
        working-directory: service
        run: go test -v ./internal/...

      - name: Integration Tests
        working-directory: service
        run: go test -v ./integration/...
