name: CI

on: push

jobs:
  build-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "15"

      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: service/node_modules
          key: node_modules-${{ runner.os }}-${{ hashFiles('service/package-lock.json') }}

      - name: Install dependencies
        working-directory: service
        run: npm install

      - name: Run tests
        working-directory: service
        run: npm test

  build-service-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: nelonoel/branch-name@v1.0.1

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: docker.pkg.github.com
          username: "publisher"
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: "${{ format('{0}/universe-service', github.repository) }}"
          image_tag: "${{ env.BRANCH_NAME }}"
          push_git_tag: true
          context: service
